In [1]:
print("hello")

hello


In [2]:
import numpy as np

In [3]:
a = [i for i in range(10)]

In [4]:
a

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]:
b = np.array(a)

In [6]:
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
a = np.array([[1,6],
             [2,8],
             [3,11],
             [3,10],
             [1,7]])

In [8]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [9]:
mean_a = np.mean(a, axis = 0)

In [10]:
mean_a

array([2. , 8.4])

In [11]:
a_centered = a - mean_a

In [12]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [13]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [14]:
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [28]:
a_centered_sp = a_centered[:,0] @ a_centered[:,1]

In [29]:
a_centered_sp

8.0

In [30]:
arn = a_centered_sp / 4

In [31]:
arn

2.0

In [33]:
np.cov(a.transpose())

array([[1. , 2. ],
       [2. , 4.3]])

In [4]:
import pandas as pd

In [7]:
authors = pd.DataFrame({'author_id':[1, 2, 3],
                    'author_name':['Тургенев', 'Чехов', 'Островский']})

In [11]:
authors

author_id author_name
0          1    Тургенев
1          2       Чехов
2          3  Островский

In [12]:
book = pd.DataFrame({'author_id':[1, 1, 1, 2, 2, 3, 3],
                     'book_title':['Отцы и дети', 'Рудин', 'Дворянское гнездо', 'Толстый и тонкий', 'Дама с собачкой', 'Гроза', 'Таланты и поклонники'],
                     'price':[450, 300, 350, 500, 450, 370, 290]})

In [13]:
book

author_id            book_title  price
0          1           Отцы и дети    450
1          1                 Рудин    300
2          1     Дворянское гнездо    350
3          2      Толстый и тонкий    500
4          2       Дама с собачкой    450
5          3                 Гроза    370
6          3  Таланты и поклонники    290

In [14]:
authors_price = pd.merge(authors, book, on = 'author_id', how = 'inner')

In [15]:
authors_price

author_id author_name            book_title  price
0          1    Тургенев           Отцы и дети    450
1          1    Тургенев                 Рудин    300
2          1    Тургенев     Дворянское гнездо    350
3          2       Чехов      Толстый и тонкий    500
4          2       Чехов       Дама с собачкой    450
5          3  Островский                 Гроза    370
6          3  Островский  Таланты и поклонники    290

In [18]:
top5 = authors_price.sort_values(by = 'price').tail(5)

In [32]:
top5

author_id author_name         book_title  price
2          1    Тургенев  Дворянское гнездо    350
5          3  Островский              Гроза    370
0          1    Тургенев        Отцы и дети    450
4          2       Чехов    Дама с собачкой    450
3          2       Чехов   Толстый и тонкий    500

In [53]:
author_name = pd.DataFrame({'author_name':authors_price['author_name'].unique()})

In [54]:
author_name

author_name
0    Тургенев
1       Чехов
2  Островский

In [87]:
min_price = authors_price.groupby('author_name').agg({'price': 'min'}).rename(columns={'price': 'min_price'})

In [88]:
min_price.reset_index(inplace = True)

In [89]:
min_price

author_name  min_price
0  Островский        290
1    Тургенев        300
2       Чехов        450

In [90]:
max_price = authors_price.groupby('author_name').agg({'price': 'max'}).rename(columns={'price': 'max_price'})

In [91]:
max_price.reset_index(inplace = True)

In [92]:
max_price

author_name  max_price
0  Островский        370
1    Тургенев        450
2       Чехов        500

In [93]:
mean_price = authors_price.groupby('author_name').agg({'price': 'mean'}).rename(columns={'price': 'mean_price'})

In [94]:
mean_price.reset_index(inplace = True)

In [101]:
mean_price

author_name  mean_price
0  Островский  330.000000
1    Тургенев  366.666667
2       Чехов  475.000000

In [111]:
min_max = pd.merge(min_price, max_price, on = 'author_name', how = 'inner')

In [112]:
min_max

author_name  min_price  max_price
0  Островский        290        370
1    Тургенев        300        450
2       Чехов        450        500

In [113]:
authors_stat = pd.merge(df43, mean_price, on = 'author_name', how = 'inner')

In [114]:
authors_stat

author_name  min_price  max_price  mean_price
0  Островский        290        370  330.000000
1    Тургенев        300        450  366.666667
2       Чехов        450        500  475.000000

In [26]:
authors_stat = pd.DataFrame({'author_name':authors_price['author_name'].unique(),
                 'min_price':authors_price.groupby('author_name').agg({'price': 'min'}),
                 'max_price':authors_price.groupby('author_name').agg({'price': 'max'}),
                 'mean_price':authors_price.groupby('author_name').agg({'price': 'mean'})})

In [29]:
authors_price['author_name'].unique()

array(['Тургенев', 'Чехов', 'Островский'], dtype=object)

In [116]:
authors_price['cover'] = ['твердая', 'мягкая', 'мягкая', 'твердая', 'твердая', 'мягкая', 'мягкая']

In [117]:
authors_price

author_id author_name            book_title  price    cover
0          1    Тургенев           Отцы и дети    450  твердая
1          1    Тургенев                 Рудин    300   мягкая
2          1    Тургенев     Дворянское гнездо    350   мягкая
3          2       Чехов      Толстый и тонкий    500  твердая
4          2       Чехов       Дама с собачкой    450  твердая
5          3  Островский                 Гроза    370   мягкая
6          3  Островский  Таланты и поклонники    290   мягкая

In [165]:
book_info = pd.pivot_table(authors_price, values = 'price', index = 'author_name',columns=['cover'], aggfunc = sum)

In [166]:
book_info.fillna(0, inplace = True)

In [167]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [168]:
book_info.to_pickle('book_info.pkl')

In [169]:
book_info2 = pd.read_pickle('book_info.pkl')

In [170]:
book_info2

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0

In [171]:
book_info

cover        мягкая  твердая
author_name                 
Островский    660.0      0.0
Тургенев      650.0    450.0
Чехов           0.0    950.0